CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR UNIQUE NOT NULL,
    phone_number VARCHAR(10) UNIQUE NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    user_password VARCHAR NOT NULL,
    user_role VARCHAR DEFAULT 'standard'
);

